[package]
name = "chip8"
version = "0.1.0"
authors = ["Olafur Bogason <olafur@genkiinstruments.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
device_query = "0.1.3"
console = "0.9.0"
piston_window = "0.105.0"